services:
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/

  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
